# Generated by Django 5.0.4 on 2025-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_word', models.CharField(choices=[('sent', 'Payment Sent'), ('account', 'Account Issues'), ('setup', 'Account Setup'), ('signup', 'Signup Bonus'), ('load', 'Load Account'), ('password', 'Password'), ('pass', 'Pass'), ('link', 'link'), ('username', 'username')], max_length=20, unique=True)),
                ('response_text', models.TextField()),
                ('notify_owner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('interval_hours', models.PositiveIntegerField(default=6)),
            ],
        ),
    ]
