# Generated by Django 5.0.4 on 2025-03-27 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='processed',
            new_name='success',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='response_time',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(choices=[('keyword', 'Keyword Response'), ('scheduled', 'Scheduled Message'), ('direct', 'Direct Message')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelog',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
