# Generated by Django 5.0.4 on 2025-03-27 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_auditlog_bot_auditlo_user_id_ab0edf_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmetrics',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'System Metrics'},
        ),
        migrations.RemoveField(
            model_name='systemmetrics',
            name='active_connections',
        ),
        migrations.RemoveField(
            model_name='systemmetrics',
            name='bot_uptime',
        ),
        migrations.RemoveField(
            model_name='systemmetrics',
            name='metrics',
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='cpu_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='disk_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='memory_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='botstatus',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botstatus',
            name='uptime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
