# Generated by Django 5.0.4 on 2025-03-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_scheduledmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='next_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
