# Generated by Django 5.0.4 on 2025-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_scheduledmessage_next_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('current_version', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
