# Generated by Django 5.0.4 on 2025-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordresponse',
            name='trigger_word',
            field=models.CharField(choices=[('sent', 'Sent'), ('account', 'Account'), ('setup', 'Setup'), ('signup', 'Bonus'), ('load', 'Load'), ('password', 'Password'), ('pass', 'Pass'), ('link', 'link'), ('cashapp', 'cashapp'), ('venmo', 'venmo'), ('chime', 'chime'), ('paypal', 'paypal')], max_length=20, unique=True),
        ),
    ]
