# Generated by Django 5.0.4 on 2025-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_keywordresponse_trigger_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordresponse',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal Response')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='keywordresponse',
            name='notify_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keywordresponse',
            name='trigger_word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
