# Generated by Django 5.0.4 on 2025-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_keywordresponse_priority_scheduledmessage_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
