# Generated by Django 5.0.4 on 2025-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_smsrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordresponse',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal Response')], default='normal', max_length=10),
        ),
    ]
