# Generated by Django 5.0.4 on 2025-03-03 07:23

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_keywordresponse_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='interval_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smsrecipient',
            name='phone',
            field=models.CharField(max_length=20, validators=[bot.models.validate_phone_number]),
        ),
    ]
