# Generated by Django 5.0.4 on 2025-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_keywordresponse_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scheduled_images/'),
        ),
    ]
